language: csharp
script:
  - dotnet restore
  - dotnet build -c Release src/tensorflow-batteries-linux-x64-cpu
  - dotnet build -c Release src/tensorflow-batteries-linux-x64-gpu
  - dotnet test -c Release --no-build test/TensorflowBinariesBuildTask.Tests
mono: none
dotnet: "3.1.405"
os:
  - linux
  #- osx
