language: csharp
script:
  - dotnet restore
  - dotnet build -c Release test/TensorflowBinariesBuildTask.Tests
  - dotnet test -c Release --no-build test/TensorflowBinariesBuildTask.Tests
mono: none
dotnet: "3.1.405"
os:
  - linux
  #- osx
